config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/signup',     to: 'users#new'
  get    '/login',      to: 'sessions#new'
  post   '/login',      to: 'sessions#create'
  delete '/logout',     to: 'sessions#destroy'
  resources :users do
    member do
      get    :following, :followers
      post   :follow
      delete :unfollow
    end
    resources :tweets,  only: [:create, :destroy]
    resources :rooms,  only: [:index, :show, :new, :create, :destroy] do
      resources :messages,  only: [:new, :create, :destroy] do
        collection do
          get :mark_read
        end
      end
    end
  end
end

app/views/partials/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    %h2
      = pluralize(object.errors.count, 'error')
      prohibited this object from being saved:
    %ul
      - object.errors.full_messages.each do |message|
        %li
          = message

app/views/partials/_footer.html.haml
%footer.footer
  %nav
    %ul
      %li 2017 twitter-clone

app/views/partials/_navbar.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  = link_to 'Twitter clone', logo_url , class: 'navbar-brand'
  %nav
    %ul.nav.navbar-nav.navbar-right
      - if logged_in?
        %li
          = link_to 'Home', user_path(current_user)
        %li
          = link_to 'Message', user_rooms_path(current_user)
        %li
          = link_to 'Users', users_path
        %li
          = link_to 'Edit Profile', edit_user_path(current_user)
        %li
          = link_to 'Log out', logout_path, method: :delete
      - else
        %li
          = link_to 'Log in', login_path

app/views/partials/_stats.html.haml
.stats
  = link_to following_user_path(@user) do
    %strong#following.stat
      = @user.following.count
    following
  = link_to followers_user_path(@user) do
    %strong#followers.stat
      = @user.followers.count
    followers