config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/signup',     to: 'users#new'
  get    '/login',      to: 'sessions#new'
  post   '/login',      to: 'sessions#create'
  delete '/logout',     to: 'sessions#destroy'
  resources :users do
    member do
      get    :following, :followers
      post   :follow
      delete :unfollow
    end
    resources :tweets,  only: [:create, :destroy]
    resources :rooms,  only: [:index, :show, :new, :create, :destroy] do
      resources :messages,  only: [:new, :create, :destroy] do
        collection do
          get :mark_read
        end
      end
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :user_rooms, inverse_of: :room
  has_many :users, through: :user_rooms
  belongs_to :create_user, class_name:  "User"
  validates :create_user_id, presence: true
  validate :check_empty_room?, on: :create
  validate :check_dup_room?, on: :create, if: :check_empty_room?

  scope :sort_by_message_created, -> do
    includes(:messages).order("messages.created_at desc")
  end

  scope :check_available, -> (state) do
    joins(:user_rooms).where(user_rooms:{available_flag: state})
  end

  def check_empty_room?
    unless user_ids_without_me(self.user_rooms.map(&:user_id)).empty?
      true
    else
      errors[:base] << 'No one is selected as room participant.'
      false
    end
  end

  def check_dup_room?
    check_flag = self.create_user.rooms.check_available(true).any? do |room|
      same_participants?(room.user_ids)
    end
    unless check_flag
      true
    else
      errors[:base] << 'Participant combination is overlapped.'
      false
    end
  end

  def delete_messages_history(user)
    self.user_rooms.find_by(user: user).delete_history
  end

  def datetime_last_history_deleted(user)
    self.user_rooms.find_by(user: user).datetime_history_deleted
  end

  def last_read_msg_id(user)
    self.user_rooms.find_by(user: user).my_last_read_msg_id
  end

  def unavailable_participant?
    count = self.user_rooms.where(user_rooms:{available_flag: false}).count
    count != 0 ? true : false
  end

  def reactivate_participant
    self.user_rooms.update_all(available_flag: true) if self.unavailable_participant?
  end

  def existing_unused_room
    self.create_user.rooms.find do |room|
      room.unavailable_participant? && same_participants?(room.users.ids)
    end
  end

  def has_unread_message?(user)
    room_latest_message_id = self.messages.order(id: :desc).first&.id
    latest_read_message_id = self.user_rooms.find_by(user: user).latest_read_message_id
    room_latest_message_id.to_i > latest_read_message_id
  end

  private
    def user_ids_without_me(user_ids)
      user_ids.reject { |user_id| user_id == self.create_user_id }
    end

    def same_participants?(room_user_ids)
      self.user_rooms.map(&:user_id).sort == room_user_ids.sort
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only:[:show, :destroy]

  def index
    @rooms = current_user.rooms.check_available(true).sort_by_message_created
  end

  def show
    @messages = @room.messages.after_history_deletion(@room.datetime_last_history_deleted(current_user))
                              .order(created_at: :desc)
    @message_post = current_user.messages.new
  end

  def new
    @room = current_user.rooms.new
  end

  def create
    @room = current_user.rooms.build(room_params)
    @room.create_user = current_user
    unused_room = @room.existing_unused_room
    if !unused_room.nil?
      unused_room.reactivate_participant
      redirect_to user_room_path(current_user, unused_room)
    elsif @room.save
      redirect_to user_room_path(current_user, @room)
    else
      render 'new'
    end
  end

  def destroy
    @room.delete_messages_history(current_user)
    redirect_to user_rooms_path(current_user), success: "Messages history deleted successfully!"
  end

  private
    def set_room
      @room = current_user.rooms.check_available(true).find(params[:id])
    end

    def room_params
      params.require(:room).permit(user_ids: [])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def room_participants(users)
    users.map(&:name).join(" / ")
  end

  def message_read_count(message)
    read_count = message.read_count(current_user)
    read_count == 0 ? "Unread" : "Read:#{read_count}"
  end

  def read_state(room)
    "--unread" if room.has_unread_message?(current_user)
  end
end

app/views/rooms/_message.haml
- @messages.reverse.each do |message|
  %li{class: "room-messages__item room-messages__item--#{message.id}"}
    .room-messages__item__avater
      = image_tag avater_url(message.user), class: 'rooms-avater'
    .room-messages__item__box
      %span.room-messages__item__box__user
        = message.user.name
        %span.room-messages__item__box__read
          - if message.user == current_user
            = message_read_count(message)
            = link_to 'delete', [message.user,@room,message], method: :delete, data: { confirm: 'Are you sure?' }, class: 'room-messages__item__box__delete'
      %span.room-messages__item__box__msg
        = simple_format(message.body)
      %span.room-messages__item__box__timestamp
        Posted #{time_ago_in_words(message.created_at)} ago.

app/views/rooms/index.html.haml
%h1 Direct Messages

.rooms-button
  = link_to 'Create Message Room', new_user_room_path(current_user), class: 'btn btn-primary'

%ul.rooms
  - @rooms.each do |room|
    = link_to user_room_path(current_user,room) do
      %li{class: "rooms__item rooms__item#{read_state(room)}"}
        .rooms__item__avater
          - room.users.each do |user|
            = image_tag avater_url(user), class: 'rooms-avater'
        .rooms__item__box
          %span.rooms__item__box__user
            = room_participants(room.users)
          %span.rooms__item__box__msg
            = room.messages.first.body unless room.messages.empty?

app/views/rooms/new.html.haml
%h1 Create Message Room

.room-form
  = simple_form_for([current_user,@room]) do |f|
    = f.button :submit, "Next" ,class: 'btn btn-primary room-button'
    = render 'partials/error_messages', object: f.object
    .room-form-list
      = f.collection_check_boxes :user_ids, User.where.not(id:current_user.id), :id, :name

app/views/rooms/show.html.haml
%h1
  Messages of 
  = room_participants(@room.users)

= link_to 'Delete messages history', [current_user,@room], method: :delete, data: { confirm: 'Are you sure?' }, class: 'room-messages__delete'

%ul.room-messages
  .room-messages__page
    = render 'rooms/message'

%section.message_form
  = render 'messages/form_new', {user: current_user, room: @room, message: @message_post}

.js-room{data: {msgid: @room.last_read_msg_id(current_user), url: mark_read_user_room_messages_path(current_user,@room)}}